---
- name: Download Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins APT repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    filename: jenkins
    state: present
    update_cache: yes

- name: Add Python APT repository
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
    update_cache: yes

- name: Install Required Packages
  apt:
    - curl
    - git
    - software-properties-common
    - python3.12
    - python3.12-venv
    - python3.12-dev
    - fontconfig
    - openjdk-17-jre
    - mingw-w64
    - g++-mingw-w64-x86-64
  state: present

- name: Set Python 3.12 as default python3
  command: update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1

- name: Download uv standalone installer
  get_url:
    url: https://astral.sh/uv/install.sh
    dest: /tmp/install-uv.sh
    mode: '0755'

- name: Run uv installer with system-wide installation
  shell: |
    export UV_NO_PROMPT=1
    export UV_INSTALL_DIR=/usr/local/bin
    /tmp/install-uv.sh
  args:
    executable: /bin/bash

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
